language: ruby
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ree

# Attempt Travis/Cassandra fix re: https://github.com/travis-ci/travis-ci/issues/1484
before_install:
#  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
#  - echo "127.0.0.1 " `hostname` | sudo tee /etc/hosts
#  - sudo service cassandra start
#  - sleep 5

install: 
  - wget https://www.tracelytics.com/install_tracelytics.sh
  - sudo sh ./install_tracelytics.sh f51e2a43-0ee5-4851-8a54-825773b3218e

before_script:
  - bundle install
  - bundle exec rake compile

services: 
  - mongodb
  - memcached
#  - cassandra

