language: ruby

cache:
  bundler: true
  directories:
  - vendor/bundle

env:
  - DBTYPE=postgresql
  - DBTYPE=mysql2
  - DBTYPE=mysql

rvm:
  - 2.6.0-rc2
  - 2.5.3
  - 2.4.5
  - 2.3.8
#  - ruby-head
#  - jruby-9.0.5.0

gemfile:
  - gemfiles/libraries.gemfile
  - gemfiles/unit.gemfile
  - gemfiles/instrumentation_mocked.gemfile
  - gemfiles/instrumentation_mocked_oldgems.gemfile
  - gemfiles/frameworks.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/delayed_job.gemfile
  - gemfiles/noop.gemfile

matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.6.0-rc2
      gemfile: gemfiles/rails42.gemfile

    - rmv: 2.6.0-rc2
      env: DBTYPE=mysql
    - rvm: 2.5.3
      env: DBTYPE=mysql
    - rvm: 2.4.5
      env: DBTYPE=mysql
    - rvm: ruby-head
      env: DBTYPE=mysql

    - gemfile: gemfiles/unit.gemfile
      env: DBTYPE=mysql
    - gemfile: gemfiles/noop.gemfile
      env: DBTYPE=mysql
    - gemfile: gemfiles/libraries.gemfile
      env: DBTYPE=mysql
    - gemfile: gemfiles/instrumentation_mocked.gemfile
      env: DBTYPE=mysql
    - gemfile: gemfiles/instrumentation_mocked_oldgems.gemfile
      env: DBTYPE=mysql
    - gemfile: gemfiles/frameworks.gemfile
      env: DBTYPE=mysql
    - gemfile: gemfiles/rails51.gemfile
      env: DBTYPE=mysql
    - gemfile: gemfiles/rails52.gemfile
      env: DBTYPE=mysql
    - gemfile: gemfiles/delayed_job.gemfile
      env: DBTYPE=mysql

    - gemfile: gemfiles/unit.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/noop.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/libraries.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/instrumentation_mocked.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/instrumentation_mocked_oldgems.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/frameworks.gemfile
      env: DBTYPE=mysql2
    - gemfile: gemfiles/delayed_job.gemfile
      env: DBTYPE=mysql2
  allow_failures:
    - rvm: ruby-head
#    - rvm: 2.6.0-rc2

# FIXME: Figure out if this is still an issue when reviewing cassandra test setup
# Attempt Travis/Cassandra fix re: https://github.com/travis-ci/travis-ci/issues/1484
# Updated Cassandra: https://github.com/travis-ci/travis-ci/issues/1650

before_install:
  - sudo service cassandra stop
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /etc/cassandra/cassandra-env.sh"
  - echo "127.0.0.1 localhost"  | sudo tee /etc/hosts
  - echo "127.0.0.1 " `hostname` | sudo tee -a /etc/hosts
  - sudo service cassandra start

install:
  - curl -LO http://kent.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz
  - tar xzf swig-3.0.8.tar.gz
  - pushd swig-3.0.8
  - ./configure && make && sudo make install
  - popd

before_script:
  - bundle update --jobs=3 --retry=3 --without development
  - bundle exec rake fetch_ext_deps
  - bundle exec rake clean
  - bundle exec rake compile
  - psql -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'create database travis_ci_test;'
  - redis-server --requirepass secret_pass &
  - sleep 10
  - export APPOPTICS_TOKEN_BUCKET_CAPACITY=1000
  - export APPOPTICS_TOKEN_BUCKET_RATE=1000

script: "N=1 bundle exec rake test"

services:
  - mongodb
  - memcached
  - cassandra
#  - redis
  - rabbitmq
